remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
title: [The title of your site]
description: [A short description of your site's purpose]
github:
  zip_url: http://example.com/download.zip
  another_url: another value
